version: '3'

services:
  dummylms:
    container_name: dummylms
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
      - keycloak
    ports:
      - "8081:8080"
      - "8090:8090"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      web:

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.4
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HOSTNAME: keycloak.local
    entrypoint: [ "/opt/keycloak/bin/kc.sh", "start-dev", "--hostname-strict-backchannel=false"]
    networks:
      web:
        aliases:
          - keycloak.local
  db:
    image: 'postgres:latest'
    container_name: db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - web

networks:
  web:
    driver: bridge